### ISSUE TITLE
Is this non-official package upgradable ?

### ISSUE THREAD

**Issue by Nokia808** [flathub/net.codeindustry.MasterPDFEditor#1]
As title said, if I buy this product from company, can I enter my license key to this package & upgrade it by this way to gain full functionality & remove watermark ?

**Comment by refi64** [comment]
AFAIK yes, there's no reason why it wouldn't work.

**Comment by muelli** [comment]
@Nokia808 can you report back, whether it worked?

**Comment by muelli** [comment]
let's assume it does work. Please reopen if it doesn't.
