### ISSUE TITLE
OCR languages aren't saved

### ISSUE THREAD

**Issue by peixe80** [flathub/net.codeindustry.MasterPDFEditor#19]
Every time I open Master PDF Editor, I go to "Document / OCR / Install language / Spanish" and it installs. But when I close and reopen the application, it's gone :-( How can I fix it? Thank you!

**Comment by muelli** [comment]
do you know where it saves it to?

**Comment by peixe80** [comment]
I'm not sure. This is the flatpak home folder:
```
~/.var/app/net.codeindustry.MasterPDFEditor$ tree
├── cache
│   ├── fontconfig
│   ├── icon-cache.kcache
│   ├── mesa_shader_cache
│   │   └── index
│   └── tmp
├── config
│   ├── Code Industry
│   │   └── Master PDF Editor 5.conf
│   ├── kdeglobals
│   └── QtProject.conf
└── data
    ├── user-places.xbel
    ├── user-places.xbel.bak
    └── user-places.xbel.tbcache
```
But when I go to "Document / OCR / Install language", this is the output at the terminal:
```
Error opening data file ~/.masterpdfeditor/tessdata/eng.traineddata
Please make sure the TESSDATA_PREFIX environment variable is set to the parent directory of your "tessdata" directory.
Failed loading language 'eng'
Tesseract couldn't load any languages!
```
The ".masterpdfeditor" folder doesn't exist in the flatpak installation.

**Comment by refi64** [comment]
Does it work if you pass --persist=~/.masterpdfeditor ?

**Comment by peixe80** [comment]
Do you mean this?
```
$ flatpak run net.codeindustry.MasterPDFEditor --persist=~/.masterpdfeditor
Master PDF Editor 5: Unknown option "persist".
```

**Comment by refi64** [comment]
Sorry for the ambiguity, I meant:

flatpak run --persist=~/.masterpdfeditor net.codeindustry.MasterPDFEditor

**Comment by peixe80** [comment]
OK. I have tried that command and it comes out the same. I have also tried the new version 5.7 and everything is the same.

**Comment by muelli** [comment]
hm. we'd need to know the path it uses to store that data in order to persist that.
That shouldn't be too difficult to find that out.
I'd open run the container with --command=bash, start the app, download the data, close the app, and try to find the data somewhere.

**Comment by peixe80** [comment]
I'm afraid I don't know how to do it...

This is what I have done, but nothing comes out:

1. I've run in terminal:

```
$ flatpak run --command=bash net.codeindustry.MasterPDFEditor
[📦 net.codeindustry.MasterPDFEditor ~]$
```
2. I've opened the app from the graphic menus.

3. I've download the "spa.zip" from the Master PDF Editor app.

4. I've run in terminal:

```
[📦 net.codeindustry.MasterPDFEditor ~]$ find -name spa.zip
$
```
5. I've closed the app.

6. I've run in terminal:

```
[📦 net.codeindustry.MasterPDFEditor ~]$ find -name spa.zip
$
```

7. Apparently it finds nothing.

**Comment by muelli** [comment]
I think it works for me.
I intend to close this soon unless you object.

**Comment by peixe80** [comment]
Yes, now it works for me too. I guess it has been fixed with some update...

**Comment by peixe80** [comment]
Yes, now it works for me too. I guess it has been fixed with some update...
