### ISSUE TITLE
Version 4.3.89 ?

### ISSUE THREAD

**Issue by go-ten** [flathub/net.codeindustry.MasterPDFEditor#24]
Hi,

This is not a problem, rather a request.
Version 4 of master PDF was really perfect. Would we have the possibility to create a flatpak of version 4.3.89? Or is it totally unthinkable

Thks

**Comment by muelli** [comment]
Creating a flatpak: yes, that's probably relatively easy.

Hosting on Flathub: hm. I remember the policy as following upstream as closely as possible. So I guess that a legacy version needs a very strong case. But since you don't care about updates, I guess you'd be fine with flatpaking and running it for yourself.

**Comment by go-ten** [comment]
thanks for the answer.

Yes, that's exactly it. I don't care about updates.
I simply have no idea how to create a flatpak. At my level I have a .deb and a .rpm. I think it should be possible to find a .tar.gz.

**Comment by muelli** [comment]
There are a few flatpaks on flathub that use .debs: https://github.com/search?q=org%3Aflathub+deb&type=code

With a tarball, though, it would probably be easier to use the existing flatpak.

**Comment by muelli** [comment]
seems they provide the old version: http://code-industry.net/public/master-pdf-editor-4.3.89_qt5.amd64.tar.gz

And now I understand, why it's more interesting. The app comes without restrictions. Yeah, maybe we can make a net.codeindustry.MasterPDFEditor4 flatpak.

You should be able to checkout the 4.3.89 branch and do a `flatpak-builder --install-deps-from=flathub --user --install --ccache --keep-build-dirs  --force-clean -v  --repo=/var/tmp/fb.repo fpbuilder net.codeindustry.MasterPDFEditor.yaml`.

**Comment by go-ten** [comment]
Yes, that's exactly it. Version 4 is the last version without any restrictions.
Here's what I did :

- I downloaded from github the .zip code for the 4.3.89 branch.
- launched the command : `flatpak-builder --install-deps-from=flathub --user --install --ccache --keep-build-dirs --force-clean -v --repo=/var/tmp/fb.repo fpbuilder`
- here is the error message :

`FB: Running: git config --get user.email
FB: Running: git config --get user.name
Dependency Sdk: org.kde.Sdk 5.15
FB: Running: flatpak --user info org.kde.Sdk/x86_64/5.15 --show-commit
Installing org.kde.Sdk/x86_64/5.15 from flathub
FB: Using Flatpak version 1.10.1
FB: Running: flatpak --user install flathub -y --noninteractive org.kde.Sdk/x86_64/5.15
error: No remote refs found similar to ‘flathub’
Error installing deps: running `flatpak --user install flathub -y --noninteractive org.kde.Sdk/x86_64/5.15`: `

Looks like he can't reach flathub.

**Comment by go-ten** [comment]
Ok I manually installed from flathub the sdk (KDE 5.15). 
Now the installation has worked.

Thank you so much

**Comment by go-ten** [comment]
just a small detail. Here is the logo of version 4
![net codeindustry MasterPDFEditor](https://user-images.githubusercontent.com/47599241/107855034-593b4f00-6e20-11eb-8f5b-a25ae5fb2164.png)

**Comment by go-ten** [comment]
Yes, that would be a good idea. I don't have good GitHub skills to edit a file like the image in a PR
