### ISSUE TITLE
Update will make you lose registration if you unshare internet

### ISSUE THREAD

**Issue by raffaem** [flathub/net.codeindustry.MasterPDFEditor#27]
I have MasterPDFEditor and was registered.

In the past I had de-authorized internet:

`sudo flatpak override net.codeindustry.MasterPDFEditor --unshare=network`

I have updated it:
`flatpak update`

After the update MasterPDFEditor lost the registration. I was back to the free unregistered version.

I closed it and re-authorized internet to insert the registration code:
`sudo flatpak override net.codeindustry.MasterPDFEditor --share=network`

Re-opening it and it was unnecessary to insert the registration code. MasterPDFEditor got registered automatically again.

It's clear when you update it lose registration and when you open it again it automatically call home to register again.

**Comment by muelli** [comment]
#1

**Comment by refi64** [comment]
This isn't really a Flatpak issue, the application likely just re-checks the license on updates. Having issues like this is sort of inherent to revoking permissions...
