### ISSUE TITLE
Missing window frame on Fedora 35

### ISSUE THREAD

**Issue by subpop** [flathub/net.codeindustry.MasterPDFEditor#48]
On Fedora 35 with GNOME, the flatpak launches in what appears to be windowless mode. I'm assuming this has something to do with Wayland. I feel like this didn't happen earlier in the Fedora 35 release cycle, so it could be something that's changed in Fedora.

![Screenshot from 2022-01-26 21-46-12](https://user-images.githubusercontent.com/153475/151282898-d891d5fa-c48b-4d3e-a56a-43e8ab653dbe.png)

**Comment by subpop** [comment]
When I disable the `wayland` socket with an override, the window frame "comes back".

`flatpak --user override net.codeindustry.MasterPDFEditor --nosocket=wayland`

**Comment by muelli** [comment]
sounds like it would make sense to disable the wayland support for now.

**Comment by muelli** [comment]
Is this still an issue with the newer runtime?

**Comment by muelli** [comment]
let me close for now. Feel free to reopen if this issue persists.
