### ISSUE TITLE
Update the org.kde.Platform

### ISSUE THREAD

**Issue by gnumanx** [flathub/net.codeindustry.MasterPDFEditor#80]
The following is the output of my flatpak installation.

```
Info: runtime org.kde.Platform branch 5.15-22.08 is end-of-life, with reason:
   We strongly recommend moving to the latest Qt 5.15-based stable version of the Platform and SDK
Info: applications using this runtime:
   net.codeindustry.MasterPDFEditor

```
Because the org.kde.Platform is available in branch 5.15-23.08, it seems to me that a little intervention could be enough. But I am only an expert user, not a developer.

Thank you very much for your hard work!

**Comment by muelli** [comment]
https://github.com/flathub/net.codeindustry.MasterPDFEditor/commit/b687058a1201a64cda4a4ef9a939b291bcb9da89
